### PR TITLE
Configuration of axis margins via the plotconfigframe

### PR DESCRIPTION
**Pull request by astyl**
Now, user can set fixed margins via the plotconfigframe

### CODE REVIEW

**Comment by newville** [comment]
@astyl I sort of liked the margin sizes to be on fractions instead of points. I'm willing to be persuaded that "points" is better, but it somehow seems a little less obvious to end users. Do you have a strong preference?

**Comment by astyl** [comment]
@newville  ,  it's the the title/labels badly shown that bother me. For example after a window resizing, I don't want to reset the margins. Actually, the feature behind the fixed margin control isn't just a simple fixed offset, it's a smart fixed offset from the edge to the box that frames the axes and its labels.
If you prefer fractions margins for wxmplot user, sure why not ? But i strongly suggest that the fraction margin is added to the current fixed margin so that there wouldn't be a bad show. And hey, user could configure both ?

**Comment by newville** [comment]
@astyl yes, I understand and appreciate the automatic setting of margins.  I think it is a big improvement.  That is not my question/point here.  

My point here is that if the user wants to tweak the automatically determined margins, they should be allowed to.  There are currently exposed ways to do this, even on the plotconfigframe, so those should either work (my preference) or be removed.  And, if they do work, should they be on fractions or pixels?  They were in fractions because I found that most natural and scaleable. Changing to pixels could be OK, but should probably be justified.  Is there a reason to prefer pixels?  

And the values shown in the plotconfigframe should almost certainly be initialized with the automatically determined values.  I'd even say there could be a checkbox for turning automatic on/off so that if the user changes title or label the margins can be automatically

**Comment by newville** [comment]
merging, but will plan on modifying

**Pull request merged**
